profil:
    resource: "@ProfilBundle/Resources/config/routing.yml"
    prefix:   /profil/

club:
    resource: "@ClubBundle/Resources/config/routing.yml"
    prefix:   /club/

comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /comment/

cart:
    resource: "@CartBundle/Resources/config/routing.yml"
    prefix:   /cart/

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event/

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /news/

tech_event:
    resource: "@TechEventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_show:
    path: /

reset_password:
    path: /resetting/request
