clubs_managment_homepage:
    path:     /clubs
    defaults: { _controller: ClubBundle:Clubs:afficherClub }
AdminClub:
    path:     /admin/club
    defaults: { _controller: ClubBundle:Clubs:AdminClub }
My_Club:
    path:     /clubs/MyClub/{id}
    defaults: { _controller: ClubBundle:Clubs:ClubPage }
Join_us:
    path:     /clubs/joinUs/{id}
    defaults: { _controller: ClubBundle:Clubs:Join }

create:
    path:     /create
    defaults: { _controller: ClubBundle:Clubs:create }

Status:
    path:     /refuse/{id}
    defaults: { _controller: ClubBundle:Clubs:StatusClub }

member:
    path:     /member/{id}
    defaults: { _controller: ClubBundle:Clubs:StatusMemberClub }

members:
    path:     /members
    defaults: { _controller: ClubBundle:Clubs:manClub }
FindClub:
    path:     /Find
    defaults: { _controller: ClubBundle:Clubs:findClub }




Theme_create:
    path:     /admin/theme
    defaults: { _controller: ClubBundle:Theme:create }
Theme_del:
    path:     /admin/theme/del{id}
    defaults: { _controller: ClubBundle:Theme:delete }
Theme_ed:
    path:     /admin/theme/edit{id}
    defaults: { _controller: ClubBundle:Theme:update }