news_notAllowed:
    path:     /notAllowed
    defaults: { _controller: NewsBundle:Default:NotAllowed }

news_domain_homepage:
    path:     /domain/
    defaults: { _controller: NewsBundle:Domain:index }

news_domain_delete:
    path:     /domain/delete/{id}
    defaults: { _controller: NewsBundle:Domain:delete }

news_domain_update:
    path:     domain/update/{id}
    defaults: { _controller: NewsBundle:Domain:update }

news_domain_search:
    path:     domain/search
    defaults: { _controller: NewsBundle:Domain:search }

news_article_add:
    path:     /article/add
    defaults: { _controller: NewsBundle:Article:add }

news_article_show:
    path:     /article/show
    defaults: { _controller: NewsBundle:Article:show }

news_article_showOne:
    path:     /article/show/{id}
    defaults: { _controller: NewsBundle:Article:showOne }

news_article_delete:
    path:   /article/delete/{id}
    defaults: { _controller: NewsBundle:Article:delete }

news_article_update:
    path:   /article/update/{id}
    defaults: { _controller: NewsBundle:Article:update }

news_article_search:
    path:   /article/search
    defaults: { _controller: NewsBundle:Article:search }

news_front_article_show:
    path:   /front/article/show
    defaults: { _controller: NewsBundle:Article:showfront }

news_front_article_showOne:
    path:     /front/article/show/{id}
    defaults: { _controller: NewsBundle:Article:showOneFront }

news_front_article_add:
    path:     /front/article/save/{id}
    defaults: { _controller: NewsBundle:Article:addBookmark }